### ISSUE TITLE
Inquire about replicating the outcome of your ERM method

### ISSUE THREAD

**Issue by LeiTong02** [CTPLab/IID_representation_learning#1]
Dear Authors:
Thanks for the great work. I am currently trying to replicating the results of your ERM method (38.47%) on Rxrx1-wilds which is reported in your paper. I following the parameter settings of your IID method but without using the style and noise injection from Restyle, the highest result I can achieve for ERM is only 35.5%. 

Can I ask that is there any other parameters should be set to achieve your reported results?
Thanks for your help in advance.

**Comment by musikisomorphie** [comment]
Dear LeiTong,

thank you for your interest in our study. Currently, I am participating in a congress event, which stops me from giving you an informative response when lots of social interactions happen. I plan to address your response asap once I back the office on Monday. Sorry for the delay.

**Comment by musikisomorphie** [comment]
Hi LeiTong,

thank you for your patient.
After checking my implementation and previous email interaction with the wilds leaderboard team, 
i think the key performance improvements of ERM come from CutMix and batch size.  If the default values of these two parameters don't achieve the reported results, you could first play with the batch size and see if it helps.

**Comment by LeiTong02** [comment]
> Hi LeiTong,
> 
> thank you for your patient. After checking my implementation and previous email interaction with the wilds leaderboard team, i think the key performance improvements of ERM come from CutMix and batch size. If the default values of these two parameters don't achieve the reported results, you could first play with the batch size and see if it helps.

Many thanks for your help, I can improve the performance of ERM to 38.31% with batch_size of 96 on my machine.
Thanks for your great work again!
